name: Run experiment

on:
  workflow_dispatch:
    inputs:
      config_name:
        description: 'Config name uploaded to AWS to be used for experiment'
        required: true
        default: 'my_conf.json'
      machines:
        description: 'Comma-separated list of machines to use for the experiment'
        required: true
        default: 'Free-A4000,Free-RTX5000,Free-RTX4000,Free-P5000'

jobs:
  gradient:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9.13'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -e .

      - name: Set PYTHONPATH
        run: echo "PYTHONPATH=$(pwd)" >> $GITHUB_ENV

      - name: Run gradient command
        env:
          GRADIENT_API_KEY: ${{ secrets.GRADIENT_API_KEY }}
          GRADIENT_PROJECT_ID: ${{ secrets.GRADIENT_PROJECT_ID }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          ACCOUNT_ID: ${{ secrets.ACCOUNT_ID }}
          BUCKET_NAME: ${{ secrets.BUCKET_NAME }}
          ROLE_NAME: ${{ secrets.ROLE_NAME }}
        run: |
          python scripts/run_gradient_command.py \
            --command "bash -c \"sleep 5m && \
                                (echo -e '\\n\\n [INFO] 5-minute period for server warm-up ended! \
                                          \\n [INFO] Starting upgrade process... \\n\\n' && \
                                sudo apt-get update && \
                                sudo apt-get install -y screen && \
                                echo -e '\\n\\n [INFO] System packages upgraded! \
                                         \\n [INFO] Upgrading pip and installing dependencies... \\n\\n' && \
                                pip freeze | egrep -v 'jdcal|jupyter' | xargs pip uninstall -y && \
                                pip freeze | xargs pip install && \
                                pip install jupyter-console && \
                                echo -e '\\n\\n [INFO] Dependencies installed! \
                                         \\n [INFO] Starting kernel session to keep workbook up... \\n\\n' && \
                                curl -s -X POST -H \\\"Authorization: token \$JUPYTER_TOKEN\\\" \
                                                \\\"https://\$PAPERSPACE_FQDN/api/kernels\\\" && \
                                echo -e '\\n\\n [INFO] Kernel started! \
                                         \\n [INFO] Downloading and setting up repository... \\n\\n' && \
                                python -m venv venv && \
                                source venv/bin/activate && \
                                git clone https://github.com/${{ github.repository }}.git && \
                                cd CryptoEvolution && \
                                pip install -r requirements.txt && \
                                pip install -e . && \
                                echo -e '\\n\\n [INFO] Repository setup complete! \
                                         \\n [INFO] Starting training process... \\n\\n' && \
                                python scripts/train_model.py --gradient --config_path s3://$BUCKET_NAME/configs/${{ github.event.inputs.config_name }})\"" \
            --env "GRADIENT_API_KEY:$GRADIENT_API_KEY,\
                  GRADIENT_PROJECT_ID:$GRADIENT_PROJECT_ID,\
                  ACCOUNT_ID:$ACCOUNT_ID,\
                  AWS_ACCESS_KEY_ID:$AWS_ACCESS_KEY_ID,\
                  AWS_SECRET_ACCESS_KEY:$AWS_SECRET_ACCESS_KEY,\
                  ROLE_NAME:$ROLE_NAME,\
                  BUCKET_NAME:$BUCKET_NAME" \
            --machines ${{ github.event.inputs.machines }}
